version: "3"

services:
  redis:
    image: redislabs/rejson:latest
    ports:
    - 6379:6379
    volumes:
      - redis_data:/data/redis
    restart: always
    # TODO: enable appendonly + load rejson module - note: entrypoint: redis-server --appendonly yes

volumes:
  redis_data:
